spring:
   application:
      name: product-service
   h2:
    console:
      enabled: true
      path: /h2
   datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
   jpa:
     hibernate:
      ddl-auto: none

server:
   port: 8080
